# you need put this file in your drone exec machine, and edit .drone.yml which command is `cd /app/ugrsicalsrv`,
# so you need `mkdir /app/ugrsicalsrv` in this machine, and put this file in this directory.
# don't forget to `mkdir configs` in this dir, and put your server.json and config.json in here, which will bind mount to docker container.
version: '3'

services:
  app:
    image: ugrsicalsrv:latest
    restart: always
      #environment:
    ports:
      - "5678:5678"
    volumes:
      - ./configs/server.json:/app/configs/server.json
      - ./configs/config.json:/app/configs/config.json
    depends_on:
      - "redis"
  redis:
    image: redis:6.2.6
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./configs/redis.conf:/etc/redis/redis.conf
      - ./data/data:/data  # need create data dir
      - ./data/logs:/logs  # need create data dir
    command: redis-server /etc/redis/redis.conf
